// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGY17sJCOW_O8A2rDn-L900hVmo6-0NqQ',
    appId: '1:968657646453:android:599a980aba55858c1d993c',
    messagingSenderId: '968657646453',
    projectId: 'flutter-firebase-eb522',
    storageBucket: 'flutter-firebase-eb522.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5Do55hkiG_xrSHZYULXDoEICvQ1wxaI',
    appId: '1:968657646453:ios:285351f5e0f5840c1d993c',
    messagingSenderId: '968657646453',
    projectId: 'flutter-firebase-eb522',
    storageBucket: 'flutter-firebase-eb522.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGY17sJCOW_O8A2rDn-L900hVmo6-0NqQ',
    appId: '1:968657646453:web:f4f90e5a9a5a5a5a5a5a5',
    messagingSenderId: '968657646453',
    projectId: 'flutter-firebase-eb522',
    storageBucket: 'flutter-firebase-eb522.firebasestorage.app',
  );

}